# Generated by Django 3.1.5 on 2021-01-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=45)),
                ('abbreviated_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('acquisition_date', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='member_of_the_division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
                ('division_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.division')),
            ],
        ),
        migrations.CreateModel(
            name='transfer_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_transfer', models.CharField(max_length=45)),
                ('equipment_inventory_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.equipment')),
                ('materially_responsible_person_idmaterially_responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.member_of_the_division')),
            ],
        ),
        migrations.CreateModel(
            name='materially_responsible_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
                ('member_of_the_division_division_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.division')),
                ('member_of_the_division_idmember_of_the_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.member_of_the_division')),
            ],
        ),
        migrations.CreateModel(
            name='Head_of_division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
                ('division_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.division')),
            ],
        ),
    ]
