# Generated by Django 3.1.5 on 2021-01-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=45)),
                ('abbreviated_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('acquisition_date', models.CharField(max_length=45)),
                ('cost', models.CharField(max_length=45)),
                ('number_of_the_room', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='member_of_the_division',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=45)),
                ('first_name', models.CharField(max_length=45)),
                ('patronymic', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=45)),
                ('division_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.division')),
            ],
        ),
        migrations.CreateModel(
            name='materially_responsible_person',
            fields=[
                ('member_of_the_division_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.member_of_the_division')),
                ('id_member_of_the_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_id', to='accounting.member_of_the_division')),
            ],
            bases=('accounting.member_of_the_division',),
        ),
        migrations.CreateModel(
            name='transfer_form',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_transfer', models.CharField(max_length=45)),
                ('number_of_the_room', models.CharField(max_length=45)),
                ('inventory_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.equipment')),
                ('mater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.materially_responsible_person')),
            ],
        ),
        migrations.CreateModel(
            name='Head_of_division',
            fields=[
                ('member_of_the_division_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.member_of_the_division')),
                ('id_member_of_the_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membe_id', to='accounting.member_of_the_division')),
            ],
            bases=('accounting.member_of_the_division',),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.materially_responsible_person'),
        ),
    ]
