# Generated by Django 3.1.5 on 2021-01-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cost',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='head_of_division',
            name='division_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisionnumbe', to='accounting.division'),
        ),
        migrations.AlterField(
            model_name='materially_responsible_person',
            name='member_of_the_division_division_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisionnum', to='accounting.division'),
        ),
        migrations.AlterField(
            model_name='materially_responsible_person',
            name='member_of_the_division_idmember_of_the_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idmember_of_the_division', to='accounting.member_of_the_division'),
        ),
        migrations.AlterField(
            model_name='member_of_the_division',
            name='division_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_number', to='accounting.division'),
        ),
        migrations.AlterField(
            model_name='transfer_form',
            name='equipment_inventory_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_number', to='accounting.equipment'),
        ),
        migrations.AlterField(
            model_name='transfer_form',
            name='materially_responsible_person_idmaterially_responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idmaterially_responsible_person', to='accounting.materially_responsible_person'),
        ),
    ]
