# Generated by Django 3.1.5 on 2021-01-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210116_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
