# Generated by Django 3.1.5 on 2021-01-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210112_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materially_responsible_person',
            old_name='member_of_the_division_division_number',
            new_name='division_number',
        ),
        migrations.AddField(
            model_name='transfer_form',
            name='number_of_the_room',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
