# Generated by Django 3.1.5 on 2021-01-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20210116_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head_of_division',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materially_responsible_person',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member_of_the_division',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transfer_form',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
