# Generated by Django 3.1.5 on 2021-01-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20210112_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materially_responsible_person',
            name='idmember_of_the_division',
        ),
        migrations.RemoveField(
            model_name='transfer_form',
            name='idmaterially_responsible_person',
        ),
        migrations.AddField(
            model_name='materially_responsible_person',
            name='id_member_of_the_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_member_of_the_division', to='accounting.member_of_the_division'),
        ),
        migrations.AddField(
            model_name='transfer_form',
            name='id_materially_responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_materially_responsible_person', to='accounting.materially_responsible_person'),
        ),
    ]
