# Generated by Django 3.1.5 on 2021-01-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20210112_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_form',
            name='id_materially_responsible_person',
        ),
        migrations.AddField(
            model_name='transfer_form',
            name='materially',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materially', to='accounting.materially_responsible_person'),
        ),
    ]
