# Generated by Django 3.1.5 on 2021-01-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20210112_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_form',
            name='materially',
        ),
        migrations.AddField(
            model_name='transfer_form',
            name='mater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mater', to='accounting.materially_responsible_person'),
        ),
    ]
