# Generated by Django 3.1.5 on 2021-01-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20210112_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head_of_division',
            name='division_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.division'),
        ),
        migrations.AlterField(
            model_name='materially_responsible_person',
            name='division_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.division'),
        ),
        migrations.AlterField(
            model_name='materially_responsible_person',
            name='id_member_of_the_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.member_of_the_division'),
        ),
        migrations.AlterField(
            model_name='member_of_the_division',
            name='division_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.division'),
        ),
        migrations.AlterField(
            model_name='transfer_form',
            name='inventory_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.equipment'),
        ),
        migrations.AlterField(
            model_name='transfer_form',
            name='mater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.materially_responsible_person'),
        ),
    ]
