# Generated by Django 3.1.5 on 2021-01-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20210112_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_of_division',
            name='id_member_of_the_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.member_of_the_division'),
        ),
    ]
